### ISSUE TITLE
`party-js-container` div is too small, confetti effects are cut off.

### ISSUE THREAD

**Issue by spencersolberg** [yiliansource/party-js#70] opened 2021-08-30 19:52 UTC
I'm using the confetti effect on my website for some buttons and when a key is pressed, but I've noticed that the confetti only goes so far into my page before being cut off. It looks like the `party-js-container` div might be at fault here, as it only covers part of my page. 
<img width="1552" alt="Screen Shot 2021-08-30 at 3 40 36 PM" src="https://user-images.githubusercontent.com/46253322/131396009-3a65c20c-8eaa-4b5a-a0ad-6d7aafa29efe.png">

Here's an example of what it looks like:

https://user-images.githubusercontent.com/46253322/131396591-8d607660-f2ea-48c8-9c6c-1af69ef33645.mp4

As you can see, the confetti gets cut off halfway through.

This issue does not seem to happen in version 2.0.0. In my experience, the `party-js-container` takes up the entire page in that version.

Thanks!

**Comment by yiliansource** [comment] 2021-08-31 14:17
Interesting, thanks for reporting!
Which version is this on exactly? Can you reproduce this in a CodeSandbox?

**Comment by spencersolberg** [comment] 2021-08-31 21:29
Hey, I'm using the latest version with JSDeliver (https://cdn.jsdelivr.net/npm/party-js@latest/bundle/party.min.js). I made a CodeSandbox with what I think is the same issue. It's a little different than my site in that the split is between the top and bottom rather than the left and right:

https://pux8m.csb.app

**Comment by yiliansource** [comment] 2021-09-01 18:51
I see, it seems that this is because it fits the particle container to the size of the DOM. You could fix this by stretching the `<body>` to be atleast the size of the viewport. Do you think this is more intuitive to be the standard behaviour? In that case I'll patch it.

**Comment by spencersolberg** [comment] 2021-09-02 20:56
It looks like my `<body>` has `max-width: 45rem` set (I think this is from the css framework I'm using), and disabling that does let the confetti work everywhere. I've made another CodeSandbox here that should highlight my issue a little bit better:

https://v9x55.csb.app/

**Comment by yiliansource** [comment] 2021-09-25 08:16
I hope this is fixed now; I'll roll out a new version later today or tomorrow with the fix!

**Closed** 2021-09-25 08:15 UTC
Labels: bug

**Comment by yiliansource** [comment] 2021-09-26 08:48
I just published `v2.1.0`, this should make it work! 😄
